/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedTenantRouteImport } from './routes/_authenticated/tenant'
import { Route as AuthenticatedLandlordRouteImport } from './routes/_authenticated/landlord'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTenantIndexRouteImport } from './routes/_authenticated/tenant/index'
import { Route as AuthenticatedLandlordIndexRouteImport } from './routes/_authenticated/landlord/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTenantTicketsRouteImport } from './routes/_authenticated/tenant/tickets'
import { Route as AuthenticatedTenantProfileRouteImport } from './routes/_authenticated/tenant/profile'
import { Route as AuthenticatedTenantPaymentsRouteImport } from './routes/_authenticated/tenant/payments'
import { Route as AuthenticatedTenantLeaseRouteImport } from './routes/_authenticated/tenant/lease'
import { Route as AuthenticatedTenantAnnouncementsRouteImport } from './routes/_authenticated/tenant/announcements'
import { Route as AuthenticatedLandlordTicketsRouteImport } from './routes/_authenticated/landlord/tickets'
import { Route as AuthenticatedLandlordTenantsRouteImport } from './routes/_authenticated/landlord/tenants'
import { Route as AuthenticatedLandlordSettingsRouteImport } from './routes/_authenticated/landlord/settings'
import { Route as AuthenticatedLandlordRoomsRouteImport } from './routes/_authenticated/landlord/rooms'
import { Route as AuthenticatedLandlordRequestsRouteImport } from './routes/_authenticated/landlord/requests'
import { Route as AuthenticatedLandlordPropertiesRouteImport } from './routes/_authenticated/landlord/properties'
import { Route as AuthenticatedLandlordPaymentsRouteImport } from './routes/_authenticated/landlord/payments'
import { Route as AuthenticatedLandlordLeasesRouteImport } from './routes/_authenticated/landlord/leases'
import { Route as AuthenticatedLandlordLabelsRouteImport } from './routes/_authenticated/landlord/labels'
import { Route as AuthenticatedLandlordAnnouncementsRouteImport } from './routes/_authenticated/landlord/announcements'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminPropertiesRouteImport } from './routes/_authenticated/admin/properties'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTenantRoute = AuthenticatedTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLandlordRoute = AuthenticatedLandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantIndexRoute =
  AuthenticatedTenantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedLandlordIndexRoute =
  AuthenticatedLandlordIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedTenantTicketsRoute =
  AuthenticatedTenantTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantProfileRoute =
  AuthenticatedTenantProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantPaymentsRoute =
  AuthenticatedTenantPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantLeaseRoute =
  AuthenticatedTenantLeaseRouteImport.update({
    id: '/lease',
    path: '/lease',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantAnnouncementsRoute =
  AuthenticatedTenantAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedLandlordTicketsRoute =
  AuthenticatedLandlordTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedLandlordTenantsRoute =
  AuthenticatedLandlordTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedLandlordSettingsRoute =
  AuthenticatedLandlordSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedLandlordRoomsRoute =
  AuthenticatedLandlordRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedLandlordRequestsRoute =
  AuthenticatedLandlordRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedLandlordPropertiesRoute =
  AuthenticatedLandlordPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedLandlordPaymentsRoute =
  AuthenticatedLandlordPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedLandlordLeasesRoute =
  AuthenticatedLandlordLeasesRouteImport.update({
    id: '/leases',
    path: '/leases',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedLandlordLabelsRoute =
  AuthenticatedLandlordLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedLandlordAnnouncementsRoute =
  AuthenticatedLandlordAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesRoute =
  AuthenticatedAdminPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/landlord': typeof AuthenticatedLandlordRouteWithChildren
  '/tenant': typeof AuthenticatedTenantRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/landlord/announcements': typeof AuthenticatedLandlordAnnouncementsRoute
  '/landlord/labels': typeof AuthenticatedLandlordLabelsRoute
  '/landlord/leases': typeof AuthenticatedLandlordLeasesRoute
  '/landlord/payments': typeof AuthenticatedLandlordPaymentsRoute
  '/landlord/properties': typeof AuthenticatedLandlordPropertiesRoute
  '/landlord/requests': typeof AuthenticatedLandlordRequestsRoute
  '/landlord/rooms': typeof AuthenticatedLandlordRoomsRoute
  '/landlord/settings': typeof AuthenticatedLandlordSettingsRoute
  '/landlord/tenants': typeof AuthenticatedLandlordTenantsRoute
  '/landlord/tickets': typeof AuthenticatedLandlordTicketsRoute
  '/tenant/announcements': typeof AuthenticatedTenantAnnouncementsRoute
  '/tenant/lease': typeof AuthenticatedTenantLeaseRoute
  '/tenant/payments': typeof AuthenticatedTenantPaymentsRoute
  '/tenant/profile': typeof AuthenticatedTenantProfileRoute
  '/tenant/tickets': typeof AuthenticatedTenantTicketsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/landlord/': typeof AuthenticatedLandlordIndexRoute
  '/tenant/': typeof AuthenticatedTenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/landlord/announcements': typeof AuthenticatedLandlordAnnouncementsRoute
  '/landlord/labels': typeof AuthenticatedLandlordLabelsRoute
  '/landlord/leases': typeof AuthenticatedLandlordLeasesRoute
  '/landlord/payments': typeof AuthenticatedLandlordPaymentsRoute
  '/landlord/properties': typeof AuthenticatedLandlordPropertiesRoute
  '/landlord/requests': typeof AuthenticatedLandlordRequestsRoute
  '/landlord/rooms': typeof AuthenticatedLandlordRoomsRoute
  '/landlord/settings': typeof AuthenticatedLandlordSettingsRoute
  '/landlord/tenants': typeof AuthenticatedLandlordTenantsRoute
  '/landlord/tickets': typeof AuthenticatedLandlordTicketsRoute
  '/tenant/announcements': typeof AuthenticatedTenantAnnouncementsRoute
  '/tenant/lease': typeof AuthenticatedTenantLeaseRoute
  '/tenant/payments': typeof AuthenticatedTenantPaymentsRoute
  '/tenant/profile': typeof AuthenticatedTenantProfileRoute
  '/tenant/tickets': typeof AuthenticatedTenantTicketsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/landlord': typeof AuthenticatedLandlordIndexRoute
  '/tenant': typeof AuthenticatedTenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/landlord': typeof AuthenticatedLandlordRouteWithChildren
  '/_authenticated/tenant': typeof AuthenticatedTenantRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/landlord/announcements': typeof AuthenticatedLandlordAnnouncementsRoute
  '/_authenticated/landlord/labels': typeof AuthenticatedLandlordLabelsRoute
  '/_authenticated/landlord/leases': typeof AuthenticatedLandlordLeasesRoute
  '/_authenticated/landlord/payments': typeof AuthenticatedLandlordPaymentsRoute
  '/_authenticated/landlord/properties': typeof AuthenticatedLandlordPropertiesRoute
  '/_authenticated/landlord/requests': typeof AuthenticatedLandlordRequestsRoute
  '/_authenticated/landlord/rooms': typeof AuthenticatedLandlordRoomsRoute
  '/_authenticated/landlord/settings': typeof AuthenticatedLandlordSettingsRoute
  '/_authenticated/landlord/tenants': typeof AuthenticatedLandlordTenantsRoute
  '/_authenticated/landlord/tickets': typeof AuthenticatedLandlordTicketsRoute
  '/_authenticated/tenant/announcements': typeof AuthenticatedTenantAnnouncementsRoute
  '/_authenticated/tenant/lease': typeof AuthenticatedTenantLeaseRoute
  '/_authenticated/tenant/payments': typeof AuthenticatedTenantPaymentsRoute
  '/_authenticated/tenant/profile': typeof AuthenticatedTenantProfileRoute
  '/_authenticated/tenant/tickets': typeof AuthenticatedTenantTicketsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/landlord/': typeof AuthenticatedLandlordIndexRoute
  '/_authenticated/tenant/': typeof AuthenticatedTenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/admin'
    | '/landlord'
    | '/tenant'
    | '/invite/$token'
    | '/rooms/$roomId'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/tickets'
    | '/admin/users'
    | '/landlord/announcements'
    | '/landlord/labels'
    | '/landlord/leases'
    | '/landlord/payments'
    | '/landlord/properties'
    | '/landlord/requests'
    | '/landlord/rooms'
    | '/landlord/settings'
    | '/landlord/tenants'
    | '/landlord/tickets'
    | '/tenant/announcements'
    | '/tenant/lease'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/tickets'
    | '/admin/'
    | '/landlord/'
    | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/invite/$token'
    | '/rooms/$roomId'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/tickets'
    | '/admin/users'
    | '/landlord/announcements'
    | '/landlord/labels'
    | '/landlord/leases'
    | '/landlord/payments'
    | '/landlord/properties'
    | '/landlord/requests'
    | '/landlord/rooms'
    | '/landlord/settings'
    | '/landlord/tenants'
    | '/landlord/tickets'
    | '/tenant/announcements'
    | '/tenant/lease'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/tickets'
    | '/admin'
    | '/landlord'
    | '/tenant'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/landlord'
    | '/_authenticated/tenant'
    | '/invite/$token'
    | '/rooms/$roomId'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/properties'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/landlord/announcements'
    | '/_authenticated/landlord/labels'
    | '/_authenticated/landlord/leases'
    | '/_authenticated/landlord/payments'
    | '/_authenticated/landlord/properties'
    | '/_authenticated/landlord/requests'
    | '/_authenticated/landlord/rooms'
    | '/_authenticated/landlord/settings'
    | '/_authenticated/landlord/tenants'
    | '/_authenticated/landlord/tickets'
    | '/_authenticated/tenant/announcements'
    | '/_authenticated/tenant/lease'
    | '/_authenticated/tenant/payments'
    | '/_authenticated/tenant/profile'
    | '/_authenticated/tenant/tickets'
    | '/_authenticated/admin/'
    | '/_authenticated/landlord/'
    | '/_authenticated/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tenant': {
      id: '/_authenticated/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof AuthenticatedTenantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/landlord': {
      id: '/_authenticated/landlord'
      path: '/landlord'
      fullPath: '/landlord'
      preLoaderRoute: typeof AuthenticatedLandlordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/': {
      id: '/_authenticated/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof AuthenticatedTenantIndexRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/landlord/': {
      id: '/_authenticated/landlord/'
      path: '/'
      fullPath: '/landlord/'
      preLoaderRoute: typeof AuthenticatedLandlordIndexRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/tenant/tickets': {
      id: '/_authenticated/tenant/tickets'
      path: '/tickets'
      fullPath: '/tenant/tickets'
      preLoaderRoute: typeof AuthenticatedTenantTicketsRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/profile': {
      id: '/_authenticated/tenant/profile'
      path: '/profile'
      fullPath: '/tenant/profile'
      preLoaderRoute: typeof AuthenticatedTenantProfileRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/payments': {
      id: '/_authenticated/tenant/payments'
      path: '/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof AuthenticatedTenantPaymentsRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/lease': {
      id: '/_authenticated/tenant/lease'
      path: '/lease'
      fullPath: '/tenant/lease'
      preLoaderRoute: typeof AuthenticatedTenantLeaseRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/announcements': {
      id: '/_authenticated/tenant/announcements'
      path: '/announcements'
      fullPath: '/tenant/announcements'
      preLoaderRoute: typeof AuthenticatedTenantAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/landlord/tickets': {
      id: '/_authenticated/landlord/tickets'
      path: '/tickets'
      fullPath: '/landlord/tickets'
      preLoaderRoute: typeof AuthenticatedLandlordTicketsRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/landlord/tenants': {
      id: '/_authenticated/landlord/tenants'
      path: '/tenants'
      fullPath: '/landlord/tenants'
      preLoaderRoute: typeof AuthenticatedLandlordTenantsRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/landlord/settings': {
      id: '/_authenticated/landlord/settings'
      path: '/settings'
      fullPath: '/landlord/settings'
      preLoaderRoute: typeof AuthenticatedLandlordSettingsRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/landlord/rooms': {
      id: '/_authenticated/landlord/rooms'
      path: '/rooms'
      fullPath: '/landlord/rooms'
      preLoaderRoute: typeof AuthenticatedLandlordRoomsRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/landlord/requests': {
      id: '/_authenticated/landlord/requests'
      path: '/requests'
      fullPath: '/landlord/requests'
      preLoaderRoute: typeof AuthenticatedLandlordRequestsRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/landlord/properties': {
      id: '/_authenticated/landlord/properties'
      path: '/properties'
      fullPath: '/landlord/properties'
      preLoaderRoute: typeof AuthenticatedLandlordPropertiesRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/landlord/payments': {
      id: '/_authenticated/landlord/payments'
      path: '/payments'
      fullPath: '/landlord/payments'
      preLoaderRoute: typeof AuthenticatedLandlordPaymentsRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/landlord/leases': {
      id: '/_authenticated/landlord/leases'
      path: '/leases'
      fullPath: '/landlord/leases'
      preLoaderRoute: typeof AuthenticatedLandlordLeasesRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/landlord/labels': {
      id: '/_authenticated/landlord/labels'
      path: '/labels'
      fullPath: '/landlord/labels'
      preLoaderRoute: typeof AuthenticatedLandlordLabelsRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/landlord/announcements': {
      id: '/_authenticated/landlord/announcements'
      path: '/announcements'
      fullPath: '/landlord/announcements'
      preLoaderRoute: typeof AuthenticatedLandlordAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties': {
      id: '/_authenticated/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPropertiesRoute: typeof AuthenticatedAdminPropertiesRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPropertiesRoute: AuthenticatedAdminPropertiesRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLandlordRouteChildren {
  AuthenticatedLandlordAnnouncementsRoute: typeof AuthenticatedLandlordAnnouncementsRoute
  AuthenticatedLandlordLabelsRoute: typeof AuthenticatedLandlordLabelsRoute
  AuthenticatedLandlordLeasesRoute: typeof AuthenticatedLandlordLeasesRoute
  AuthenticatedLandlordPaymentsRoute: typeof AuthenticatedLandlordPaymentsRoute
  AuthenticatedLandlordPropertiesRoute: typeof AuthenticatedLandlordPropertiesRoute
  AuthenticatedLandlordRequestsRoute: typeof AuthenticatedLandlordRequestsRoute
  AuthenticatedLandlordRoomsRoute: typeof AuthenticatedLandlordRoomsRoute
  AuthenticatedLandlordSettingsRoute: typeof AuthenticatedLandlordSettingsRoute
  AuthenticatedLandlordTenantsRoute: typeof AuthenticatedLandlordTenantsRoute
  AuthenticatedLandlordTicketsRoute: typeof AuthenticatedLandlordTicketsRoute
  AuthenticatedLandlordIndexRoute: typeof AuthenticatedLandlordIndexRoute
}

const AuthenticatedLandlordRouteChildren: AuthenticatedLandlordRouteChildren = {
  AuthenticatedLandlordAnnouncementsRoute:
    AuthenticatedLandlordAnnouncementsRoute,
  AuthenticatedLandlordLabelsRoute: AuthenticatedLandlordLabelsRoute,
  AuthenticatedLandlordLeasesRoute: AuthenticatedLandlordLeasesRoute,
  AuthenticatedLandlordPaymentsRoute: AuthenticatedLandlordPaymentsRoute,
  AuthenticatedLandlordPropertiesRoute: AuthenticatedLandlordPropertiesRoute,
  AuthenticatedLandlordRequestsRoute: AuthenticatedLandlordRequestsRoute,
  AuthenticatedLandlordRoomsRoute: AuthenticatedLandlordRoomsRoute,
  AuthenticatedLandlordSettingsRoute: AuthenticatedLandlordSettingsRoute,
  AuthenticatedLandlordTenantsRoute: AuthenticatedLandlordTenantsRoute,
  AuthenticatedLandlordTicketsRoute: AuthenticatedLandlordTicketsRoute,
  AuthenticatedLandlordIndexRoute: AuthenticatedLandlordIndexRoute,
}

const AuthenticatedLandlordRouteWithChildren =
  AuthenticatedLandlordRoute._addFileChildren(
    AuthenticatedLandlordRouteChildren,
  )

interface AuthenticatedTenantRouteChildren {
  AuthenticatedTenantAnnouncementsRoute: typeof AuthenticatedTenantAnnouncementsRoute
  AuthenticatedTenantLeaseRoute: typeof AuthenticatedTenantLeaseRoute
  AuthenticatedTenantPaymentsRoute: typeof AuthenticatedTenantPaymentsRoute
  AuthenticatedTenantProfileRoute: typeof AuthenticatedTenantProfileRoute
  AuthenticatedTenantTicketsRoute: typeof AuthenticatedTenantTicketsRoute
  AuthenticatedTenantIndexRoute: typeof AuthenticatedTenantIndexRoute
}

const AuthenticatedTenantRouteChildren: AuthenticatedTenantRouteChildren = {
  AuthenticatedTenantAnnouncementsRoute: AuthenticatedTenantAnnouncementsRoute,
  AuthenticatedTenantLeaseRoute: AuthenticatedTenantLeaseRoute,
  AuthenticatedTenantPaymentsRoute: AuthenticatedTenantPaymentsRoute,
  AuthenticatedTenantProfileRoute: AuthenticatedTenantProfileRoute,
  AuthenticatedTenantTicketsRoute: AuthenticatedTenantTicketsRoute,
  AuthenticatedTenantIndexRoute: AuthenticatedTenantIndexRoute,
}

const AuthenticatedTenantRouteWithChildren =
  AuthenticatedTenantRoute._addFileChildren(AuthenticatedTenantRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLandlordRoute: typeof AuthenticatedLandlordRouteWithChildren
  AuthenticatedTenantRoute: typeof AuthenticatedTenantRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLandlordRoute: AuthenticatedLandlordRouteWithChildren,
  AuthenticatedTenantRoute: AuthenticatedTenantRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
